name = "rumah-keripik-web"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2026-07-25"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_APP_URL = "https://rumah-keripik-web.pages.dev"
