import fs from 'fs';
import path from 'path';
import { createClient } from '@libsql/client/web';

function loadEnvLocal() {
  const envPath = path.join(process.cwd(), '.env.local');
  if (!fs.existsSync(envPath)) return;
  const content = fs.readFileSync(envPath, 'utf8');
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const index = trimmed.indexOf('=');
    if (index <= 0) continue;
    process.env[trimmed.slice(0, index).trim()] = trimmed.slice(index + 1).trim();
  }
}

function sqlQuote(value: unknown): string {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'boolean') return value ? '1' : '0';
  if (value instanceof Uint8Array || value instanceof ArrayBuffer) {
    const bytes = value instanceof Uint8Array ? value : new Uint8Array(value);
    return `X'${Buffer.from(bytes).toString('hex')}'`;
  }
  const s = String(value);
  return `'${s.replace(/'/g, "''")}'`;
}

async function dumpDatabase(): Promise<void> {
  loadEnvLocal();
  const url = process.env.TURSO_DATABASE_URL?.replace(/^libsql:\/\//, 'https://');
  const authToken = process.env.TURSO_AUTH_TOKEN;
  if (!url || !authToken) throw new Error('TURSO_DATABASE_URL dan TURSO_AUTH_TOKEN wajib ada.');

  const client = createClient({ url, authToken });
  const backupDir = path.join(process.cwd(), 'backups');
  fs.mkdirSync(backupDir, { recursive: true });

  const stamp = new Date().toISOString().replace(/[:.]/g, '-');
  const sqlPath = path.join(backupDir, `backup-${stamp}.sql`);
  const lines: string[] = [];
  lines.push(`-- Rumah Keripik database snapshot ${new Date().toISOString()}`);
  lines.push(`-- Generated by backup-turso.ts (logical dump via @libsql/client). Restore: sqlite3 atau turso db shell < file.sql`);
  lines.push(`-- foreign_keys=OFF saat restore: urutan INSERT alfabetis tidak mengikuti dependensi FK; integritas dijamin snapshot.`);
  lines.push('PRAGMA foreign_keys=OFF;');
  lines.push('');

  const tablesResult = await client.execute(
    `SELECT name, sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name`
  );

  let totalRows = 0;
  for (const t of tablesResult.rows) {
    const tableName = String(t.name);
    const createSql = String(t.sql || '');
    lines.push(createSql.endsWith(';') ? createSql : `${createSql};`);
    lines.push('');

    const info = await client.execute(`PRAGMA table_info("${tableName.replace(/"/g, '""')}")`);
    const columns = info.rows.map((c) => String(c.name));

    let offset = 0;
    let chunkRows: Array<Record<string, unknown>> = [];
    do {
      const page = await client.execute(
        `SELECT * FROM "${tableName.replace(/"/g, '""')}" LIMIT 500 OFFSET ${offset}`
      );
      chunkRows = page.rows as Array<Record<string, unknown>>;
      if (chunkRows.length === 0) break;
      for (const row of chunkRows) {
        const values = columns.map((col) => sqlQuote(row[col]));
        const colList = columns.map((col) => `"${col.replace(/"/g, '""')}"`).join(', ');
        lines.push(`INSERT INTO "${tableName.replace(/"/g, '""')}" (${colList}) VALUES (${values.join(', ')});`);
        totalRows += 1;
      }
      offset += chunkRows.length;
    } while (chunkRows.length === 500);
    lines.push('');
  }

  const indexResult = await client.execute(
    `SELECT name, tbl_name, sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL ORDER BY name`
  );
  for (const idx of indexResult.rows) {
    const createSql = String(idx.sql || '');
    lines.push(createSql.endsWith(';') ? createSql : `${createSql};`);
  }
  lines.push('');

  fs.writeFileSync(sqlPath, lines.join('\n'), 'utf8');
  client.close();

  const metaPath = path.join(backupDir, `backup-${stamp}.json`);
  fs.writeFileSync(
    metaPath,
    JSON.stringify(
      {
        createdAt: new Date().toISOString(),
        tables: tablesResult.rows.length,
        totalRows,
        sqlFile: path.basename(sqlPath),
        sizeBytes: fs.statSync(sqlPath).size,
        restoreHint: 'Restore: buat DB baru lalu jalankan file .sql ini (CREATE TABLE + INSERT).',
      },
      null,
      2
    ),
    'utf8'
  );

  console.log(`Backup metadata written: ${metaPath}`);
  console.log(`SQL backup written: ${sqlPath}`);
  console.log(`Tables: ${tablesResult.rows.length}, rows: ${totalRows}, size: ${fs.statSync(sqlPath).size} bytes`);
}

dumpDatabase().catch((error) => {
  console.error('Backup failed:', error);
  process.exit(1);
});